[tool.poetry]
name = "c-bank"
version = "0.1.0"
description = ""
authors = ["egor <shievanov@bk.ru>"]
readme = "README.md"
packages = [{include = "c_bank"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
